/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aER2iu3ulll
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function CourseWithCards() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6 space-y-8">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Nuestros Cursos</h2>
          <p className="max-w-[700px] mx-auto text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Explora nuestros cursos de alta calidad y encuentra el que mejor se adapte a tus necesidades.
          </p>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-950 dark:text-gray-50">
            <img
              alt="Curso 1"
              className="rounded-t-lg w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-bold">Curso de Programación Web</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Aprende a crear sitios web modernos y responsive con HTML, CSS y JavaScript.
              </p>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Inscríbete
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-950 dark:text-gray-50">
            <img
              alt="Curso 2"
              className="rounded-t-lg w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-bold">Curso de Diseño Gráfico</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Aprende a crear diseños impactantes y profesionales con Photoshop y Illustrator.
              </p>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Inscríbete
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-950 dark:text-gray-50">
            <img
              alt="Curso 3"
              className="rounded-t-lg w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-bold">Curso de Marketing Digital</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Aprende a promocionar tu negocio en línea y aumentar tus ventas.
              </p>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Inscríbete
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
