/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aER2iu3ulll
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function CourseWithCards() {
  return (
    <section className="text-[#30313D] w-full py-12 md:py-24 lg:py-32 bg-white">
      <div className="flex flex-col px-10 gap-8">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Nuestros Cursos
          </h2>
          <p className="max-w-[700px] mx-auto text-[#30313D] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Explora nuestros cursos de alta calidad y encuentra el que mejor se
            adapte a tus necesidades.
          </p>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
          <div className="bg-white rounded-lg shadow-md dark:text-gray-50">
            <img
              alt="Curso 1"
              className="rounded-t-lg w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-4 space-y-2">
              <h3 className="text-[#30313D] text-lg font-bold">
                Curso de Programación Web
              </h3>
              <p className="text-[#30313D]">
                Aprende a crear sitios web modernos y responsive con HTML, CSS y
                JavaScript.
              </p>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#06AB78] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#0e7490] focus:outline-none focus:ring-2 focus:ring-[#0891b2] focus:ring-offset-2"
                href="#"
              >
                Inscríbete
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:text-gray-50">
            <img
              alt="Curso 2"
              className="rounded-t-lg w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-4 space-y-2">
              <h3 className="text-[#30313D] text-lg font-bold">
                Curso de Diseño Gráfico
              </h3>
              <p className="text-[#30313D]">
                Aprende a crear diseños impactantes y profesionales con
                Photoshop y Illustrator.
              </p>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#06AB78] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#0e7490] focus:outline-none focus:ring-2 focus:ring-[#0891b2] focus:ring-offset-2"
                href="#"
              >
                Inscríbete
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:text-gray-50">
            <img
              alt="Curso 3"
              className="rounded-t-lg w-full object-cover"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/200",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="p-4 space-y-2">
              <h3 className="text-[#30313D] text-lg font-bold">
                Curso de Marketing Digital
              </h3>
              <p className="text-[#30313D]">
                Aprende a promocionar tu negocio en línea y aumentar tus ventas.
              </p>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#06AB78] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#0e7490] focus:outline-none focus:ring-2 focus:ring-[#0891b2] focus:ring-offset-2"
                href="#"
              >
                Inscríbete
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
