/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6wU8sSU2ciY
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TitleWithImages() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-white">
      <div className="container mx-auto grid items-center justify-center gap-6 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-[#30313D] text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Explore Our Products
          </h2>
          <p className="mx-auto max-w-[700px] text-[#30313D] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Discover our high-quality products that are designed to meet your
            needs.
          </p>
        </div>
        <div className="grid w-full grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:gap-8">
          <div className="relative overflow-hidden rounded-lg">
            <img
              alt="Product 1"
              className="aspect-[4/3] w-full object-cover transition-all duration-300 hover:scale-105"
              height="300"
              src="/placeholder.svg"
              width="400"
            />
          </div>
          <div className="relative overflow-hidden rounded-lg">
            <img
              alt="Product 2"
              className="aspect-[4/3] w-full object-cover transition-all duration-300 hover:scale-105"
              height="300"
              src="/placeholder.svg"
              width="400"
            />
          </div>
          <div className="relative overflow-hidden rounded-lg">
            <img
              alt="Product 3"
              className="aspect-[4/3] w-full object-cover transition-all duration-300 hover:scale-105"
              height="300"
              src="placeholder.svg"
              width="400"
            />
          </div>
        </div>
      </div>
    </section>
  );
}
