/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lyBA40gETdw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function LeadMailList() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-[#F8F9FD]">
      <div className="container mx-auto px-4 md:px-6">
        <div className="flex flex-col items-center space-y-6 text-center">
          <div className="space-y-3">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none text-[#30313D]">
              Emails pendejos
            </h1>
            <p className="max-w-[600px] text-[#30313D] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Suscríbete y recibe pensamientos que escribo para mí
            </p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <form className="flex space-x-2">
              <Input
                className="max-w-lg flex-1 bg-white"
                placeholder="Enter your email"
                type="email"
              />
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#06AB78] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#0e7490] focus:outline-none focus:ring-2 focus:ring-[#0891b2] focus:ring-offset-2"
                href="#"
              >
                Suscribite
              </Link>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
}
