/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5MXyVpEOpGg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function FooterMinimalist() {
  return (
    <footer className="bg-gray-100 py-6 dark:bg-gray-800">
      <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 sm:flex-row sm:gap-0">
        <p className="text-sm text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="flex items-center gap-4">
          <Link className="text-sm hover:underline dark:text-gray-400" href="#">
            Privacy Policy
          </Link>
          <Link className="text-sm hover:underline dark:text-gray-400" href="#">
            Terms of Service
          </Link>
        </nav>
      </div>
    </footer>
  )
}
