/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TulEuFN1rMJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function DiscoverWithCheckPoints() {
  return (
    <section className="bg-[#F8F9FD] w-full py-12 md:py-24 lg:py-32">
      <div className="flex justify-around">
        <div className="space-y-8 xl:space-y-10">
          <div className="space-y-4 lg:space-y-6">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl xl:text-4xl">
                <span className="text-[#30313D]">Put* el que no lea</span>{" "}
                <span className="text-indigo-500 dark:text-indigo-400">
                  quién soy
                </span>
              </h2>
              <ul className="space-y-4 text-gray-500 dark:text-gray-400">
                <li className="flex items-center space-x-2">
                  <CircleCheckIcon className="h-5 w-5 text-indigo-500 dark:text-indigo-400" />
                  <span>Escribí lo de arriba solo para picar tu ego.</span>
                </li>
                <li className="flex items-center space-x-2">
                  <CircleCheckIcon className="h-5 w-5 text-indigo-500 dark:text-indigo-400" />
                  <span>
                    No me gusta describirme porque no creo en las etiquetas.
                  </span>
                </li>
                <li className="flex items-center space-x-2">
                  <CircleCheckIcon className="h-5 w-5 text-indigo-500 dark:text-indigo-400" />
                  <span>
                    Me llaman Diego pero yo me llamo Huracán a memesmooo.
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="space-y-8 lg:space-y-10">
          <img
            alt="Image"
            className="aspect-square overflow-hidden rounded-xl object-cover"
            src="/placeholder.svg"
            width="400"
          />
        </div>
      </div>
    </section>
  );
}

function CircleCheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}
