/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TulEuFN1rMJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function DiscoverWithCheckPoints() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
        <div className="space-y-8 xl:space-y-10">
          <div className="space-y-4 lg:space-y-6">
            <div className="space-y-2">
              <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl xl:text-4xl">
                <span className="text-gray-900 dark:text-gray-50">
                  Impulsa tu
                </span>
                {""}
                <span className="text-indigo-500 dark:text-indigo-400">
                  negocio
                </span>
              </h2>
              <ul className="space-y-2 text-gray-500 dark:text-gray-400">
                <li className="flex items-center space-x-2">
                  <CircleCheckIcon className="h-5 w-5 text-indigo-500 dark:text-indigo-400" />
                  <span>Aumenta tu visibilidad en línea</span>
                </li>
                <li className="flex items-center space-x-2">
                  <CircleCheckIcon className="h-5 w-5 text-indigo-500 dark:text-indigo-400" />
                  <span>Mejora tu presencia digital</span>
                </li>
                <li className="flex items-center space-x-2">
                  <CircleCheckIcon className="h-5 w-5 text-indigo-500 dark:text-indigo-400" />
                  <span>Atrae más clientes potenciales</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="space-y-8 lg:space-y-10">
          <img
            alt="Image"
            className="aspect-square w-full overflow-hidden rounded-xl object-cover"
            height="650"
            src="/placeholder.svg"
            width="650"
          />
        </div>
      </div>
    </section>
  );
}

function CircleCheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}
