/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/t9uBgtr9VJa
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Eczar } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

eczar({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function DiscoverWithBulletPoints() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
        <div className="space-y-8">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
              <span className="text-indigo-500">Discover</span>
              {""}
              <span className="text-gray-900 dark:text-gray-50">
                the power of our platform
              </span>
            </h2>
            <ul className="space-y-2 text-gray-500 dark:text-gray-400">
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-indigo-500" />
                <span>Scalable infrastructure</span>
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-indigo-500" />
                <span>Cutting-edge technology</span>
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-indigo-500" />
                <span>Exceptional customer support</span>
              </li>
            </ul>
          </div>
        </div>
        <div className="flex items-center justify-center">
          <img
            alt="Image"
            className="aspect-square overflow-hidden rounded-xl object-cover"
            height={400}
            src="/placeholder.svg"
            width={400}
          />
        </div>
      </div>
    </section>
  );
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
