/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VpG7PV6Bb9V
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function SimplePricingWithBackground() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container mx-auto px-4 md:px-6 text-center">
        <div className="max-w-2xl mx-auto space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Pricing
          </h2>
          <p className="text-gray-500 md:text-xl dark:text-gray-400">
            Choose the plan that fits your needs. No hidden fees, ever.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-10">
          <Card className="bg-white dark:bg-gray-950 p-6 rounded-lg shadow-md">
            <CardHeader>
              <h3 className="text-2xl font-bold">Starter</h3>
              <p className="text-4xl font-bold mt-2">$9</p>
              <p className="text-gray-500 dark:text-gray-400 mt-1">per month</p>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>1 user</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>5 GB storage</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>Basic analytics</p>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Get Started</Button>
            </CardFooter>
          </Card>
          <Card className="bg-white dark:bg-gray-950 p-6 rounded-lg shadow-md">
            <CardHeader>
              <h3 className="text-2xl font-bold">Pro</h3>
              <p className="text-4xl font-bold mt-2">$19</p>
              <p className="text-gray-500 dark:text-gray-400 mt-1">per month</p>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>5 users</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>50 GB storage</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>Advanced analytics</p>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Get Started</Button>
            </CardFooter>
          </Card>
          <Card className="bg-white dark:bg-gray-950 p-6 rounded-lg shadow-md">
            <CardHeader>
              <h3 className="text-2xl font-bold">Enterprise</h3>
              <p className="text-4xl font-bold mt-2">$49</p>
              <p className="text-gray-500 dark:text-gray-400 mt-1">per month</p>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>Unlimited users</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>Unlimited storage</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p>Enterprise-grade analytics</p>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Get Started</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </section>
  );
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
