/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VpG7PV6Bb9V
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function SimplePricingWithBackground() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-[#F8F9FD]">
      <div className="container mx-auto px-4 md:px-6 text-center">
        <div className="max-w-2xl mx-auto space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-[#30313D]">
            Pricing
          </h2>
          <p className="text-[#30313D]  md:text-xl ">
            Start achieving your goals today.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-10">
          <Card className="bg-white p-6 rounded-lg shadow-md">
            <CardHeader>
              <h3 className="text-[#30313D] text-2xl font-bold">Starter</h3>
              <p className="text-[#30313D] text-4xl font-bold mt-2">$49</p>
              <p className="text-[#30313D]  dark:text-gray-400 mt-1">
                per month
              </p>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">Access to basic SaaS tools</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">Email support</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">Monthly software updates</p>
              </div>
            </CardContent>
            <CardFooter>
              <Button variant="link" className="bg-[#06AB78] w-full">
                Get Started
              </Button>
            </CardFooter>
          </Card>
          <Card className="bg-white p-6 rounded-lg shadow-md">
            <CardHeader>
              <h3 className="text-[#30313D] text-2xl font-bold">
                Professional
              </h3>
              <p className="text-[#30313D] text-4xl font-bold mt-2">$99</p>
              <p className="text-[#30313D]  dark:text-gray-400 mt-1">
                per month
              </p>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">Full access to all SaaS tools</p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">
                  Priority email and chat support
                </p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">
                  Weekly software updates and new features
                </p>
              </div>
            </CardContent>
            <CardFooter>
              <Button
                variant="link"
                className="text-[#06AB78] bg-[#06AB78] w-full"
              >
                Get Started
              </Button>
            </CardFooter>
          </Card>
          <Card className="bg-white p-6 rounded-lg shadow-md">
            <CardHeader>
              <h3 className="text-[#30313D] text-2xl font-bold">Enterprise</h3>
              <p className="text-[#30313D] text-4xl font-bold mt-2">$199</p>
              <p className="text-[#30313D]  dark:text-gray-400 mt-1">
                per month
              </p>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">
                  Access to advanced and customized SaaS tools
                </p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">
                  Dedicated 24/7 support via phone
                </p>
              </div>
              <div className="flex items-center space-x-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                <p className="text-[#30313D]">
                  Real-time updates and solutions
                </p>
              </div>
            </CardContent>
            <CardFooter>
              <Button
                variant="link"
                className="text-[#06AB78] bg-[#06AB78] w-full"
              >
                Get Started
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </section>
  );
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
